#############################################################################
# Makefile for building: mypyd
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  QtStaticToPydExample.pro
# Template: lib
# Command: E:\Code\QtStatic\5.15.2\bin\qmake.exe -o Makefile QtStaticToPydExample.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:\Code\QtStatic\5.15.2\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = E:\Code\QtStatic\5.15.2\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = E:\Code\QtStatic\5.15.2\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: QtStaticToPydExample.pro E:/Code/QtStatic/5.15.2/mkspecs/win32-g++/qmake.conf E:/Code/QtStatic/5.15.2/mkspecs/features/spec_pre.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/qdevice.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/features/device_config.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/common/sanitize.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/common/gcc-base.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/common/g++-base.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/common/angle.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/win32/windows_vulkan_sdk.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/common/windows-vulkan.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/common/g++-win32.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/common/windows-desktop.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/qconfig.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_concurrent.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_core.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_core_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_dbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_dbus_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_gui.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_gui_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_help.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_help_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_network.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_network_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_printsupport.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialport.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialport_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_sql.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_sql_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_testlib.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_testlib_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_uiplugin.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_uitools.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_uitools_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_webchannel.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_websockets.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_websockets_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_widgets.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_widgets_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_winextras.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_winextras_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xml.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xml_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_zlib_private.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qdirect2d.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qgif.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qicns.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qico.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qjpeg.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qminimal.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qoffscreen.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qsqlite.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtga.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtiff.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtsysteccanbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtvectorcanbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwbmp.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwebp.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwindows.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		E:/Code/QtStatic/5.15.2/mkspecs/features/qt_functions.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/qt_config.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/win32-g++/qmake.conf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		E:/Code/QtStatic/5.15.2/mkspecs/features/exclusive_builds.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/toolchain.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/default_pre.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/win32/default_pre.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/resolve_config.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/exclusive_builds_post.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/default_post.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/precompile_header.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/warn_on.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/qt.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/gc_binaries.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/resources_functions.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/resources.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/moc.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/qmake_use.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/file_copies.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/win32/windows.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/testcase_targets.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/exceptions.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/yacc.prf \
		E:/Code/QtStatic/5.15.2/mkspecs/features/lex.prf \
		QtStaticToPydExample.pro \
		E:/Code/QtStatic/5.15.2/lib/Qt5Core.prl \
		E:/Code/QtStatic/5.15.2/lib/Qt5Gui.prl \
		E:/Code/QtStatic/5.15.2/lib/Qt5Widgets.prl \
		E:/Code/QtStatic/5.15.2/plugins/platforms/qwindows.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qgif.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qicns.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qico.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qjpeg.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qtga.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qtiff.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qwbmp.prl \
		E:/Code/QtStatic/5.15.2/plugins/imageformats/qwebp.prl \
		E:/Code/QtStatic/5.15.2/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile QtStaticToPydExample.pro
E:/Code/QtStatic/5.15.2/mkspecs/features/spec_pre.prf:
E:/Code/QtStatic/5.15.2/mkspecs/qdevice.pri:
E:/Code/QtStatic/5.15.2/mkspecs/features/device_config.prf:
E:/Code/QtStatic/5.15.2/mkspecs/common/sanitize.conf:
E:/Code/QtStatic/5.15.2/mkspecs/common/gcc-base.conf:
E:/Code/QtStatic/5.15.2/mkspecs/common/g++-base.conf:
E:/Code/QtStatic/5.15.2/mkspecs/common/angle.conf:
E:/Code/QtStatic/5.15.2/mkspecs/features/win32/windows_vulkan_sdk.prf:
E:/Code/QtStatic/5.15.2/mkspecs/common/windows-vulkan.conf:
E:/Code/QtStatic/5.15.2/mkspecs/common/g++-win32.conf:
E:/Code/QtStatic/5.15.2/mkspecs/common/windows-desktop.conf:
E:/Code/QtStatic/5.15.2/mkspecs/qconfig.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_concurrent.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_concurrent_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_core.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_core_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_dbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_dbus_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_edid_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_fb_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_gui.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_gui_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_help.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_help_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_network.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_network_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_printsupport.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_printsupport_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialbus_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialport.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_serialport_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_sql.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_sql_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_testlib.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_testlib_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_theme_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_uiplugin.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_uitools.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_uitools_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_webchannel.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_webchannel_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_websockets.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_websockets_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_widgets.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_widgets_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_winextras.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_winextras_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xml.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xml_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_lib_zlib_private.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qdirect2d.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qgenericbearer.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qgif.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qicns.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qico.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qjpeg.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qminimal.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qoffscreen.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qsqlite.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qsqlodbc.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtga.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtiff.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtsysteccanbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qttinycanbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtvectorcanbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwbmp.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwebp.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwindows.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qwindowsvistastyle.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
E:/Code/QtStatic/5.15.2/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
E:/Code/QtStatic/5.15.2/mkspecs/features/qt_functions.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/qt_config.prf:
E:/Code/QtStatic/5.15.2/mkspecs/win32-g++/qmake.conf:
E:/Code/QtStatic/5.15.2/mkspecs/features/spec_post.prf:
.qmake.stash:
E:/Code/QtStatic/5.15.2/mkspecs/features/exclusive_builds.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/toolchain.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/default_pre.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/win32/default_pre.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/resolve_config.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/exclusive_builds_post.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/default_post.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/precompile_header.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/warn_on.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/qt.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/gc_binaries.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/resources_functions.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/resources.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/moc.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/qmake_use.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/file_copies.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/win32/windows.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/testcase_targets.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/exceptions.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/yacc.prf:
E:/Code/QtStatic/5.15.2/mkspecs/features/lex.prf:
QtStaticToPydExample.pro:
E:/Code/QtStatic/5.15.2/lib/Qt5Core.prl:
E:/Code/QtStatic/5.15.2/lib/Qt5Gui.prl:
E:/Code/QtStatic/5.15.2/lib/Qt5Widgets.prl:
E:/Code/QtStatic/5.15.2/plugins/platforms/qwindows.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qgif.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qicns.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qico.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qjpeg.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qtga.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qtiff.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qwbmp.prl:
E:/Code/QtStatic/5.15.2/plugins/imageformats/qwebp.prl:
E:/Code/QtStatic/5.15.2/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile QtStaticToPydExample.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) D:\Projects\C++\QtStaticToPydExample\mypyd_plugin_import.cpp .qmake.stash libmypyd.a

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
